const USER_CONFIG = {
    "APP_ID":"wx455c71d2aa69526d",
    "APP_SECRET":"0b2587b309facefb0470f54b08bf41a3",
    "IS_SHOW_COLOR":true,"CALLBACK_TEMPLATE_ID":"",
    "CALLBACK_USERS":[
        {
            "name":"自己",
            "id":"oTMJv6bYoM-HSCy0xEjv3Vlt-cOA"
        }
    ],
    "USERS":[
        {
            "name":"静静",
            "id":"oTMJv6bYoM-HSCy0xEjv3Vlt-cOA",
            "useTemplateId":"i4iq5lOQJVEX1QcafQzIRWX9kDLF2IEogL4eFQ7tItQ",
            "province":"山东",
            "city":"临沂",
            "horoscopeDate":"01-19",
            "horoscopeDateType":"今日",
            "openUrl":"https://weibo.com/newlogin?tabtype=search&openLoginLayer=0&url=",
            "festivals":[{"type":"*生日","name":"静静","date":"01-19","year":"2000"}],
            "customizedDateList":[]
                }   
            ],
    "SWITCH":{
        "weather":true,
        "holidaytts":false,
        "CIBA":false,
        "oneTalk":false,
        "earthyLoveWords":false,
        "momentCopyrighting":false,
        "poisonChickenSoup":false,
        "poetry":false,
        "horoscope":true,
        "birthdayMessage":true,
        }
    }
  module.exports = USER_CONFIG  
